# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1f02ce92e1ad839050161b1f19c0b72d555a55259de750e068104ef565e4c6647195b114556db84991cd98c2bb480b90b8cd4d8ae28a41245e29ac4d840e989

test:
  secret_key_base: e46eaf9337cd93b56f954c30ec6148fe1a5381903c447b32f7dd389a84790c58afc318e4a08241e6324ef3108bfbd832839f0a1d0e83a87cc372fdc85ed718c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
